# Generated by Django 6.0.4 on 2026-05-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(max_length=20, verbose_name='Код (ОКСО)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('seats_budget', models.IntegerField(default=0, verbose_name='Бюджетных мест')),
                ('seats_paid', models.IntegerField(default=0, verbose_name='Платных мест')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Стоимость в год')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
    ]
