# Generated by Django 6.0.4 on 2026-05-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='base',
            field=models.CharField(choices=[('9', 'На базе 9 классов'), ('11', 'На базе 11 классов')], default='9', max_length=2, verbose_name='База образования'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='duration_months',
            field=models.IntegerField(default=10, verbose_name='Месяцев обучения'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='duration_years',
            field=models.IntegerField(default=3, verbose_name='Лет обучения'),
        ),
    ]
